export const mockNavBar = [
  {
    'CSS Basic': [
      'CSS Introduction',
      'CSS Syntax',
      'CSS How to',
      'CSS Background',
      'CSS Text',
      'CSS Font',
      'CSS Border',
      'CSS Outline',
      'CSS Marign',
      'CSS Padding',
      'CSS List',
      'CSS Table',
    ],
  },
  {
    'CSS Advanced': [
      'CSS Dimension',
      'CSS Classification',
      'CSS Positionng',
      'CSS Pseudo-class',
      'CSS Pseudo-element',
      'CSS Image Gallery',
      'CSS Image Opacity',
      'CSS Media Types',
      "CSS Dont's",
      'CSS Padding',
      'CSS List',
      'CSS Table',
    ],
  },

  { 'CSS Examples': ['CSS Examples'] },
  {
    References: [
      'CSS Advanced',
      'CSS Dimension',
      'CSS Classification',
      'CSS Positionng',
      'CSS Pseudo-class',
      'CSS Pseudo-element',
      'CSS Image Gallery',
      'CSS Image Opacity',
      'CSS Media Types',
      "CSS Dont's",
      'CSS Padding',
      'CSS List',
      'CSS Table',
    ],
  },
  { 'CSS Quiz': ['CSS Quiz', 'CSS Exam'] },
];
